default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: megan_development
  username: root
  password: <%= ENV["DB_PASSWORD"]  %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>